<a href="https://colab.research.google.com/github/vinaykotadiya/ev-adoption-forecast/blob/main/ZEVs_Forcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd

In [24]:
data = "df_VEH0120_UK.csv"

In [27]:
data = pd.read_csv(data)

In [28]:
data.head()

,BodyType,Make,GenModel,Model,Fuel,LicenceStatus,2025Q1,2024Q4,2024Q3,2024Q2,...,2016Q4,2016Q3,2016Q2,2016Q1,2015Q4,2015Q3,2015Q2,2015Q1,2014Q4,2014Q3
0,Cars,ABARTH,ABARTH 124,124 GT MULTIAIR,Petrol,Licensed,15,14,15,16,...,0,0,0,0,0,0,0,0,0,0
1,Cars,ABARTH,ABARTH 124,124 GT MULTIAIR,Petrol,SORN,4,5,4,3,...,0,0,0,0,0,0,0,0,0,0
2,Cars,ABARTH,ABARTH 124,124 GT MULTIAIR AUTO,Petrol,Licensed,26,25,27,25,...,0,0,0,0,0,0,0,0,0,0
3,Cars,ABARTH,ABARTH 124,124 GT MULTIAIR AUTO,Petrol,SORN,3,4,2,2,...,0,0,0,0,0,0,0,0,0,0
4,Cars,ABARTH,ABARTH SPIDER,124 SPIDER MULTIAIR,Petrol,Licensed,973,960,978,978,...,155,100,0,0,0,0,0,0,0,0

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208751 entries, 0 to 208750
Data columns (total 49 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   BodyType       208751 non-null  object
 1   Make           208751 non-null  object
 2   GenModel       208749 non-null  object
 3   Model          208751 non-null  object
 4   Fuel           208751 non-null  object
 5   LicenceStatus  208751 non-null  object
 6   2025Q1         208751 non-null  int64
 7   2024Q4         208751 non-null  int64
 8   2024Q3         208751 non-null  int64
 9   2024Q2         208751 non-null  int64
 10  2024Q1         208751 non-null  int64
 11  2023Q4         208751 non-null  int64
 12  2023Q3         208751 non-null  int64
 13  2023Q2         208751 non-null  int64
 14  2023Q1         208751 non-null  int64
 15  2022Q4         208751 non-null  int64
 16  2022Q3         208751 non-null  int64
 17  2022Q2         208751 non-null  int64
 18  2022Q1         208751 non-null  int64
 19  2021Q4         208751 non-null  int64
 20  2021Q3         208751 non-null  int64
 21  2021Q2         208751 non-null  int64
 22  2021Q1         208751 non-null  int64
 23  2020Q4         208751 non-null  int64
 24  2020Q3         208751 non-null  int64
 25  2020Q2         208751 non-null  int64
 26  2020Q1         208751 non-null  int64
 27  2019Q4         208751 non-null  int64
 28  2019Q3         208751 non-null  int64
 29  2019Q2         208751 non-null  int64
 30  2019Q1         208751 non-null  int64
 31  2018Q4         208751 non-null  int64
 32  2018Q3         208751 non-null  int64
 33  2018Q2         208751 non-null  int64
 34  2018Q1         208751 non-null  int64
 35  2017Q4         208751 non-null  int64
 36  2017Q3         208751 non-null  int64
 37  2017Q2         208751 non-null  int64
 38  2017Q1         208751 non-null  int64
 39  2016Q4         208751 non-null  int64
 40  2016Q3         208751 non-null  int64
 41  2016Q2         208751 non-null  int64
 42  2016Q1         208751 non-null  int64
 43  2015Q4         208751 non-null  int64
 44  2015Q3         208751 non-null  int64
 45  2015Q2         208751 non-null  int64
 46  2015Q1         208751 non-null  int64
 47  2014Q4         208751 non-null  int64
 48  2014Q3         208751 non-null  int64
dtypes: int64(43), object(6)
memory usage: 78.0+ MB

In [30]:
data.columns

Index(['BodyType', 'Make', 'GenModel', 'Model', 'Fuel', 'LicenceStatus',
       '2025Q1', '2024Q4', '2024Q3', '2024Q2', '2024Q1', '2023Q4', '2023Q3',
       '2023Q2', '2023Q1', '2022Q4', '2022Q3', '2022Q2', '2022Q1', '2021Q4',
       '2021Q3', '2021Q2', '2021Q1', '2020Q4', '2020Q3', '2020Q2', '2020Q1',
       '2019Q4', '2019Q3', '2019Q2', '2019Q1', '2018Q4', '2018Q3', '2018Q2',
       '2018Q1', '2017Q4', '2017Q3', '2017Q2', '2017Q1', '2016Q4', '2016Q3',
       '2016Q2', '2016Q1', '2015Q4', '2015Q3', '2015Q2', '2015Q1', '2014Q4',
       '2014Q3'],
      dtype='object')

In [31]:
data.describe()

,2025Q1,2024Q4,2024Q3,2024Q2,2024Q1,2023Q4,2023Q3,2023Q2,2023Q1,2022Q4,...,2016Q4,2016Q3,2016Q2,2016Q1,2015Q4,2015Q3,2015Q2,2015Q1,2014Q4,2014Q3
count,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,...,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000,208751.000000
mean,232.993092,231.604994,231.336803,230.393229,228.909677,227.888719,226.739307,225.537746,223.923459,223.675139,...,202.696696,201.541803,199.649415,197.966803,196.214428,194.795800,192.753917,190.423011,189.531265,190.548802
std,1737.173082,1738.787009,1742.933895,1743.668013,1741.636233,1743.654819,1743.001449,1744.032737,1742.733960,1747.455060,...,1789.652296,1788.226302,1784.114934,1781.190666,1780.478542,1779.637926,1772.588431,1766.300425,1762.949474,1781.506416
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,6.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.000000,4.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,52.000000,51.000000,50.000000,49.000000,48.000000,48.000000,46.000000,45.000000,44.000000,44.000000,...,23.000000,21.000000,20.000000,20.000000,19.000000,17.000000,16.000000,15.000000,15.000000,14.000000
max,350863.000000,353717.000000,355787.000000,358218.000000,360227.000000,363416.000000,364777.000000,366833.000000,368420.000000,371188.000000,...,379576.000000,375111.000000,370653.000000,366485.000000,360927.000000,355987.000000,347929.000000,341742.000000,328343.000000,323369.000000

In [35]:
data[].isnull().sum()

BodyType         0
Make             0
GenModel         2
Model            0
Fuel             0
LicenceStatus    0
2025Q1           0
2024Q4           0
2024Q3           0
2024Q2           0
2024Q1           0
2023Q4           0
2023Q3           0
2023Q2           0
2023Q1           0
2022Q4           0
2022Q3           0
2022Q2           0
2022Q1           0
2021Q4           0
2021Q3           0
2021Q2           0
2021Q1           0
2020Q4           0
2020Q3           0
2020Q2           0
2020Q1           0
2019Q4           0
2019Q3           0
2019Q2           0
2019Q1           0
2018Q4           0
2018Q3           0
2018Q2           0
2018Q1           0
2017Q4           0
2017Q3           0
2017Q2           0
2017Q1           0
2016Q4           0
2016Q3           0
2016Q2           0
2016Q1           0
2015Q4           0
2015Q3           0
2015Q2           0
2015Q1           0
2014Q4           0
2014Q3           0
dtype: int64

In [37]:
data['GenModel'].isnull().sum()

np.int64(2)